# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bp.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\005evoBP',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08\x62p.proto\"\x15\n\x05\x62prog\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"B\n\nIndividual\x12\x12\n\ngeneration\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x14\n\x04\x63ode\x18\x03 \x01(\x0b\x32\x06.bprog\"4\n\x11\x45valuationRequest\x12\x1f\n\nindividual\x18\x01 \x01(\x0b\x32\x0b.Individual\"\xe0\x01\n\x12\x45valuationResponse\x12\x0c\n\x04wins\x18\x01 \x01(\x01\x12\r\n\x05\x64raws\x18\x02 \x01(\x01\x12\x0e\n\x06losses\x18\x03 \x01(\x01\x12\x19\n\x11\x62locks_violations\x18\x04 \x01(\x01\x12\x0e\n\x06misses\x18\x05 \x01(\x01\x12\x0e\n\x06\x62locks\x18\x06 \x01(\x01\x12\x11\n\tdeadlocks\x18\x07 \x01(\x01\x12\r\n\x05\x66orks\x18\x08 \x01(\x01\x12\x0f\n\x07\x62lock_v\x18\t \x03(\x01\x12\r\n\x05win_v\x18\n \x03(\x01\x12\x0e\n\x06\x66ork_v\x18\x0b \x03(\x01\x12\x10\n\x08requests\x18\x0c \x03(\x01\x32H\n\x11\x45valuationService\x12\x33\n\x08\x45valuate\x12\x12.EvaluationRequest\x1a\x13.EvaluationResponseB\x07\n\x05\x65voBPb\x06proto3'
)




_BPROG = _descriptor.Descriptor(
  name='bprog',
  full_name='bprog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='bprog.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=33,
)


_INDIVIDUAL = _descriptor.Descriptor(
  name='Individual',
  full_name='Individual',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='generation', full_name='Individual.generation', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='Individual.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='Individual.code', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=101,
)


_EVALUATIONREQUEST = _descriptor.Descriptor(
  name='EvaluationRequest',
  full_name='EvaluationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='individual', full_name='EvaluationRequest.individual', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=155,
)


_EVALUATIONRESPONSE = _descriptor.Descriptor(
  name='EvaluationResponse',
  full_name='EvaluationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wins', full_name='EvaluationResponse.wins', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='draws', full_name='EvaluationResponse.draws', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='losses', full_name='EvaluationResponse.losses', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blocks_violations', full_name='EvaluationResponse.blocks_violations', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='misses', full_name='EvaluationResponse.misses', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blocks', full_name='EvaluationResponse.blocks', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deadlocks', full_name='EvaluationResponse.deadlocks', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='forks', full_name='EvaluationResponse.forks', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block_v', full_name='EvaluationResponse.block_v', index=8,
      number=9, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='win_v', full_name='EvaluationResponse.win_v', index=9,
      number=10, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fork_v', full_name='EvaluationResponse.fork_v', index=10,
      number=11, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requests', full_name='EvaluationResponse.requests', index=11,
      number=12, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=382,
)

_INDIVIDUAL.fields_by_name['code'].message_type = _BPROG
_EVALUATIONREQUEST.fields_by_name['individual'].message_type = _INDIVIDUAL
DESCRIPTOR.message_types_by_name['bprog'] = _BPROG
DESCRIPTOR.message_types_by_name['Individual'] = _INDIVIDUAL
DESCRIPTOR.message_types_by_name['EvaluationRequest'] = _EVALUATIONREQUEST
DESCRIPTOR.message_types_by_name['EvaluationResponse'] = _EVALUATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

bprog = _reflection.GeneratedProtocolMessageType('bprog', (_message.Message,), {
  'DESCRIPTOR' : _BPROG,
  '__module__' : 'bp_pb2'
  # @@protoc_insertion_point(class_scope:bprog)
  })
_sym_db.RegisterMessage(bprog)

Individual = _reflection.GeneratedProtocolMessageType('Individual', (_message.Message,), {
  'DESCRIPTOR' : _INDIVIDUAL,
  '__module__' : 'bp_pb2'
  # @@protoc_insertion_point(class_scope:Individual)
  })
_sym_db.RegisterMessage(Individual)

EvaluationRequest = _reflection.GeneratedProtocolMessageType('EvaluationRequest', (_message.Message,), {
  'DESCRIPTOR' : _EVALUATIONREQUEST,
  '__module__' : 'bp_pb2'
  # @@protoc_insertion_point(class_scope:EvaluationRequest)
  })
_sym_db.RegisterMessage(EvaluationRequest)

EvaluationResponse = _reflection.GeneratedProtocolMessageType('EvaluationResponse', (_message.Message,), {
  'DESCRIPTOR' : _EVALUATIONRESPONSE,
  '__module__' : 'bp_pb2'
  # @@protoc_insertion_point(class_scope:EvaluationResponse)
  })
_sym_db.RegisterMessage(EvaluationResponse)


DESCRIPTOR._options = None

_EVALUATIONSERVICE = _descriptor.ServiceDescriptor(
  name='EvaluationService',
  full_name='EvaluationService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=384,
  serialized_end=456,
  methods=[
  _descriptor.MethodDescriptor(
    name='Evaluate',
    full_name='EvaluationService.Evaluate',
    index=0,
    containing_service=None,
    input_type=_EVALUATIONREQUEST,
    output_type=_EVALUATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVALUATIONSERVICE)

DESCRIPTOR.services_by_name['EvaluationService'] = _EVALUATIONSERVICE

# @@protoc_insertion_point(module_scope)
